version: "3"
services:
  vendure-database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: vendure
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
  vendure-typesense:
    image: typesense/typesense:0.24.0
    command: ["--data-dir", "/data", "--api-key", "SuperSecret"]
    ports:
      - 8108:8108
    volumes:
      - typesense_data:/data

volumes:
  typesense_data:
  postgres_data:
  vendure_assets: